//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWTCG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Decks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Decks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWTCG.Decks", typeof(Decks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;deck id=&quot;0001&quot;&gt;
        ///	&lt;card name=&quot;General Lightsbane&quot; count=&quot;1&quot; /&gt;
        ///	&lt;card name=&quot;Banshee Soulclaimer&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;Crypt Fiend&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;Malefic Necromancer&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;Marauding Geist&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;Plague Eruptor&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;Ymirheim Chosen Warrior&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;Arctic Blast&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;A Hero&apos;s Burden&quot; count=&quot;4&quot; /&gt;
        ///	&lt;card name=&quot;That&apos;s Abominable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string decks {
            get {
                return ResourceManager.GetString("decks", resourceCulture);
            }
        }
    }
}
