//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWTCG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWTCG.Sets", typeof(Sets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Badge of Justice, Class Starter Decks&quot; id=&quot;62c00b84-9384-4e93-ba78-6326775badd7&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    
        ///     &lt;card id=&quot;14678501-a39b-548d-7a64-7253bba01e38&quot; name=&quot;Band of Channeled Magic&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Badge of Justice 1/4&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Item&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;2&quot; /&gt;
        ///      &lt;property name=&quot;Fac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string badge_of_justice_css {
            get {
                return ResourceManager.GetString("badge_of_justice_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Black Temple&quot; id=&quot;2dc7e633-fa8f-72d9-bd39-db294eac1443&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    &lt;card id=&quot;e82e21c5-cecb-8cce-556b-86d3706775a5&quot; name=&quot;Arcing Smash&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Raid - 19/23&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Ability&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;2&quot; /&gt;
        ///      &lt;property name=&quot;Faction&quot; value=&quot;Neutral&quot; /&gt;
        ///      &lt;property name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Blacktemple {
            get {
                return ResourceManager.GetString("Blacktemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Crafting Redemption,Arena Grand Melee&quot; id=&quot;3ee16cde-18d9-eeda-37c7-e7a80076828f&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    &lt;card id=&quot;c12a8b04-2270-d64a-3ac7-5b236957076c&quot; name=&quot;Alchemist&apos;s Stone&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Crafting Redemption 11/20&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Item&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;2&quot; /&gt;
        ///      &lt;property name=&quot;Faction&quot; va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CR_AGM_WoLK {
            get {
                return ResourceManager.GetString("CR_AGM_WoLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Darkmoon Faire&quot; id=&quot;7678d786-a860-431c-8b60-1f7a9ba1f10f&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    
        ///    &lt;card id=&quot;8785dc58-6980-89c0-4a4d-0caa998d3b42&quot; name=&quot;Blastenheimer 5000 Ultra Cannon&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Darkmoon Faire 1/5&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Ability&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;7&quot; /&gt;
        ///      &lt;property name=&quot;Faction&quot; value=&quot;Ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string darkmoon_faire {
            get {
                return ResourceManager.GetString("darkmoon_faire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;DeathKnight Starter Deck&quot; id=&quot;391cce0c-8414-2c94-83d3-8e680828d692&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    &lt;card id=&quot;1ba64cfb-b102-baac-da6f-13d7112f0782&quot; name=&quot;Ahkara&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;13/27&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Ally&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;5&quot; /&gt;
        ///      &lt;property name=&quot;ATK&quot; value=&quot;3&quot; /&gt;
        ///      &lt;property name=&quot;Health&quot; value= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeathKnightStarter {
            get {
                return ResourceManager.GetString("DeathKnightStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Fields Of Honor&quot; id=&quot;87cfa788-1b56-e5ba-8f01-859575792974&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;d1fb4acd-251d-406f-864e-f01b6238a01f&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/options&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FOH {
            get {
                return ResourceManager.GetString("FOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Feast of Winterveil, Burning Crusade&quot; id=&quot;fcd66545-660a-4001-9968-310595789757&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///&lt;cards&gt;
        ///&lt;card id=&quot;4d526c28-2d66-c91c-b99d-bc45bdad4a68&quot; name=&quot;Gingerbread Cookie&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Feast of Winterveil 7/20&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Item&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;3&quot; /&gt;
        ///      &lt;property name=&quot;Faction&quot; value=&quot;Neut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fow_Bc {
            get {
                return ResourceManager.GetString("Fow_Bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!--Created with .o8s Creator by KuraiTenshi--&gt;
        ///&lt;set name=&quot;Icecrown&quot; id=&quot;9777743b-522b-475a-2833-62239835a334&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;faf3e79e-e28f-4b69-a402-724752494caf&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Icecrown {
            get {
                return ResourceManager.GetString("Icecrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Magtheridons Lair Loot&quot; id=&quot;3ec04da7-bbca-4d33-8b08-f97e50e82664&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///&lt;card id=&quot;b029d492-bc8b-7291-cacd-c017a73202fb&quot; name=&quot;A&apos;dal&apos;s Signet of Defense&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Loot - 8/20&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Item&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;1&quot; /&gt;
        ///      &lt;property name=&quot;Faction&quot; value=&quot;Neutral&quot; /&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magtheridons_Lair_Loot {
            get {
                return ResourceManager.GetString("Magtheridons_Lair_Loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Magtheridons Lair Raid&quot; id=&quot;c5e3796d-2634-944e-4c92-ab8891736781&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    &lt;card id=&quot;84a29bc4-694d-7b2a-75b9-13855573d450&quot; name=&quot;Abyssal Reinforcements&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Raid - 3/43&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Ability&quot; /&gt;
        ///      &lt;property name=&quot;Cost&quot; value=&quot;3&quot; /&gt;
        ///      &lt;property name=&quot;Rules&quot; value=&quot;Put an Abyssal all [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magtheridons_Lair_Raid {
            get {
                return ResourceManager.GetString("Magtheridons_Lair_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Molten Core Raid&quot; id=&quot;9ffaceae-740d-dc0f-7253-71936720b235&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///&lt;cards&gt;
        ///&lt;card id=&quot;49f30b65-4a4f-2dbf-e598-836c0a9378f2&quot; name=&quot;Lucifron&quot;&gt;
        ///&lt;property name=&quot;Card Number&quot; value=&quot;Raid - 1/53&quot; /&gt;
        ///&lt;property name=&quot;Type&quot; value=&quot;Hero&quot; /&gt;
        ///&lt;property name=&quot;Cost&quot; value=&quot;&quot; /&gt;
        ///&lt;property name=&quot;ATK&quot; value=&quot;&quot; /&gt;
        ///&lt;property name=&quot;Health&quot; value=&quot;6&quot; /&gt;
        ///&lt;property name=&quot;Faction&quot; value=&quot;&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MC_Raid {
            get {
                return ResourceManager.GetString("MC_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Molten Core Treasure&quot; id=&quot;f4bf118a-3636-4caa-b4f2-ea931776156e&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///&lt;cards&gt;
        ///&lt;card id=&quot;f1ffe6ad-b824-da9b-8c9f-b791504bbded&quot; name=&quot;Eskhandar&apos;s Right Claw&quot;&gt;
        ///&lt;property name=&quot;Card Number&quot; value=&quot;Treasure - 21/30&quot; /&gt;
        ///&lt;property name=&quot;Type&quot; value=&quot;Weapon&quot; /&gt;
        ///&lt;property name=&quot;Cost&quot; value=&quot;3&quot; /&gt;
        ///&lt;property name=&quot;ATK&quot; value=&quot;1&quot; /&gt;
        ///&lt;property name=&quot;Health&quot; value=&quot;&quot; /&gt;
        ///&lt;propert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MC_Treasure {
            get {
                return ResourceManager.GetString("MC_Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Naxxramas Treasure&quot; id=&quot;5c48d39e-049b-ccc7-75df-e858848c3b11&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;cards&gt;
        ///    &lt;card id=&quot;a6e22a4e-98b4-c258-0b14-4b231172cd49&quot; name=&quot;Andarius the Damned&quot;&gt;
        ///      &lt;property name=&quot;Card Number&quot; value=&quot;Treasure - 6/40&quot; /&gt;
        ///      &lt;property name=&quot;Type&quot; value=&quot;Hero&quot; /&gt;
        ///      &lt;property name=&quot;Health&quot; value=&quot;28&quot; /&gt;
        ///      &lt;property name=&quot;Faction&quot; value=&quot;Horde&quot; /&gt;
        ///      &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NaxxramasTreasure {
            get {
                return ResourceManager.GetString("NaxxramasTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Onyxia&apos;s Lair Raid&quot; id=&quot;7006ab4b-5c4c-31c8-b0a9-9dbde8a0a874&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///&lt;cards&gt;
        ///&lt;card id=&quot;edb2e0cf-0290-db57-db12-5504b7f281d4&quot; name=&quot;Onyxia1&quot;&gt;
        ///&lt;property name=&quot;Card Number&quot; value=&quot;Raid - 1/33&quot; /&gt;
        ///&lt;property name=&quot;Type&quot; value=&quot;Hero&quot; /&gt;
        ///&lt;property name=&quot;Cost&quot; value=&quot;&quot; /&gt;
        ///&lt;property name=&quot;ATK&quot; value=&quot;&quot; /&gt;
        ///&lt;property name=&quot;Health&quot; value=&quot;20&quot; /&gt;
        ///&lt;property name=&quot;Faction&quot; value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Onyxia_Raid {
            get {
                return ResourceManager.GetString("Onyxia_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Onyxia&apos;s Lair Treasure&quot; id=&quot;29bc03c7-6b8b-4cb8-8473-2eb03abf676a&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///&lt;cards&gt;
        ///&lt;card id=&quot;ef519f33-2bb4-b251-1f42-6c0568172460&quot; name=&quot;Arcane Revelation&quot;&gt;
        ///&lt;property name=&quot;Card Number&quot; value=&quot;Treasure - 1/33&quot; /&gt;
        ///&lt;property name=&quot;Type&quot; value=&quot;Ability&quot; /&gt;
        ///&lt;property name=&quot;Cost&quot; value=&quot;3&quot; /&gt;
        ///&lt;property name=&quot;ATK&quot; value=&quot;&quot; /&gt;
        ///&lt;property name=&quot;Health&quot; value=&quot;&quot; /&gt;
        ///&lt;property na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Onyxia_Treasure {
            get {
                return ResourceManager.GetString("Onyxia_Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;ScourgeWar&quot; id=&quot;a67226d7-2e69-6aeb-9d35-4e964fc0e0e6&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///  &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;9481e140-e17b-4f78-90ec-0757e1ed4a6b&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/options&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScourgeWar {
            get {
                return ResourceManager.GetString("ScourgeWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Blood of Gladiators&quot; id=&quot;11c87ab0-9df5-4eae-8d3a-a3376de84188&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;cd0ae77f-5851-4556-bccf-f7cfa57f7b2c&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/options&gt;
        ///     &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_BoG {
            get {
                return ResourceManager.GetString("WoW_BoG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Drums of War&quot; id=&quot;05eccee9-6581-ef4b-9c55-b4ca725a4e71&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///     &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;db95bd1e-df0a-4894-b7e7-bb0a0cca6ae1&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/opt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_DoW {
            get {
                return ResourceManager.GetString("WoW_DoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Fires of Outland&quot; id=&quot;042e1dcf-5684-2f23-a5fb-e32f991d18b6&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;c5ed6873-1918-42d2-9d2e-7ea89f977a17&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/op [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_FoO {
            get {
                return ResourceManager.GetString("WoW_FoO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Hunt for Illidan&quot; id=&quot;58a37700-2bfd-b646-96ce-c723eb850d1c&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.0&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;b25a5dca-213b-4d48-927e-0a831fb2616d&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/options&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_HfI {
            get {
                return ResourceManager.GetString("WoW_HfI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Heroes of Azeroth&quot; id=&quot;d7e6fd4f-5252-4C4C-4A4A-64e4f56a16b5&quot; 
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;1ced7b57-5c39-4782-98bf-7c667f3a4c4b&quot;&gt;
        ///  	  &lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_HoA {
            get {
                return ResourceManager.GetString("WoW_HoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;March of the legion&quot; id=&quot;742a0866-5fdb-2ea9-27d7-70d7e05a2173&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;346372ae-9a6c-428f-b680-9aa1a97627ac&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_MoL {
            get {
                return ResourceManager.GetString("WoW_MoL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Servant of the Betrayer&quot; id=&quot;a6d03495-b80b-0a85-81e8-e602027016c1&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;00609003-6981-47cf-becf-866a3c027f2d&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_SoB {
            get {
                return ResourceManager.GetString("WoW_SoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Through The Dark Portal&quot; id=&quot;03ca4935-8770-2436-3489-d266b2eade4c&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;6bece93f-9f35-43fc-bf4b-c3fcd8c1f4a3&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_TDP {
            get {
                return ResourceManager.GetString("WoW_TDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Tokens&quot; id=&quot;23227063-0d27-4396-b63f-340d0fa8b975&quot;
        ///     gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///	 &lt;packaging&gt;
        ///	 &lt;pack name=&quot;Tokens&quot; id=&quot;f2fb36d8-c4de-4443-b12a-723f3e48fff5&quot;&gt;
        ///      &lt;pick qty=&quot;unlimited&quot; key=&quot;Faction&quot; value=&quot;Token&quot; /&gt;
        ///    &lt;/pack&gt;
        ///	&lt;/packaging&gt;
        ///&lt;cards&gt;
        ///&lt;card id=&quot;fc341db4-efc6-46c3-9f86-99370535a9e7&quot; name=&quot;Alliance Dwarf Warrior&quot;&gt;
        ///&lt;property name=&quot;Card Number&quot; value=&quot;Tokens - 1/41&quot; /&gt;
        ///&lt;prope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WoW_Tokens {
            get {
                return ResourceManager.GetString("WoW_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;set name=&quot;Wrathgate&quot; id=&quot;f4d285f6-e63a-75ce-41d5-2d0a8ad4d74a&quot; gameId=&quot;d7e6fd4f-5252-4C4C-4A4A-a645c4d8e45f&quot; gameVersion=&quot;1.0&quot; version=&quot;1.1&quot;&gt;
        ///   &lt;packaging&gt;
        ///    &lt;pack name=&quot;Booster&quot; id=&quot;e58803d5-c12c-49ca-abef-975f5e94b517&quot;&gt;
        ///  	&lt;options&gt;
        ///   	 &lt;option probability=&quot;0.125&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;E&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	 &lt;option probability=&quot;0.875&quot;&gt;
        ///      &lt;pick qty=&quot;1&quot; key=&quot;Rarity&quot; value=&quot;R&quot; /&gt;
        ///  	 &lt;/option&gt;
        ///  	&lt;/options&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wrathgate {
            get {
                return ResourceManager.GetString("Wrathgate", resourceCulture);
            }
        }
    }
}
